//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancialPlanner.Data.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FinancialPlanner.Data.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source={0};initial catalog={1};User ID={2};Password={3}.
        /// </summary>
        internal static string CONNSTRING {
            get {
                return ResourceManager.GetString("CONNSTRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enAdmin.
        /// </summary>
        internal static string CONTEXT_ADMIN {
            get {
                return ResourceManager.GetString("CONTEXT_ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enItemDetail.
        /// </summary>
        internal static string CONTEXT_ITEMDETAIL {
            get {
                return ResourceManager.GetString("CONTEXT_ITEMDETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to metadata=res://*/Entity.{0}.csdl|res://*/Entity.{0}.ssdl|res://*/Entity.{0}.msl;provider=System.Data.SqlClient;provider connection string=&apos;{1};MultipleActiveResultSets=true;&apos;.
        /// </summary>
        internal static string EFMETADATASTRING {
            get {
                return ResourceManager.GetString("EFMETADATASTRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source={0};AttachDbFilename=|DataDirectory|\{1}.mdf;Integrated Security=True.
        /// </summary>
        internal static string LOCALDBSTRING {
            get {
                return ResourceManager.GetString("LOCALDBSTRING", resourceCulture);
            }
        }
    }
}
