//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancialPlanner.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FinancialPlanner.Web.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admin@financialplanner.net.
        /// </summary>
        internal static string ADMINNAME {
            get {
                return ResourceManager.GetString("ADMINNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abc123*.
        /// </summary>
        internal static string ADMINPASSWORD {
            get {
                return ResourceManager.GetString("ADMINPASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string ADMINROLENAME {
            get {
                return ResourceManager.GetString("ADMINROLENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FinancialPlanner.
        /// </summary>
        internal static string CONN_AZURE_DATABASE {
            get {
                return ResourceManager.GetString("CONN_AZURE_DATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @89UIor#-jk.
        /// </summary>
        internal static string CONN_AZURE_PASSWORD {
            get {
                return ResourceManager.GetString("CONN_AZURE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pn5745kjcc.database.windows.net.
        /// </summary>
        internal static string CONN_AZURE_SERVER {
            get {
                return ResourceManager.GetString("CONN_AZURE_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rdonalson@pn5745kjcc.
        /// </summary>
        internal static string CONN_AZURE_USERID {
            get {
                return ResourceManager.GetString("CONN_AZURE_USERID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string CONN_DIRECTION {
            get {
                return ResourceManager.GetString("CONN_DIRECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FinancialPlannerLocalDb.
        /// </summary>
        internal static string CONN_LCLDB_DATABASE {
            get {
                return ResourceManager.GetString("CONN_LCLDB_DATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (LocalDb)\v11.0.
        /// </summary>
        internal static string CONN_LCLDB_SERVER {
            get {
                return ResourceManager.GetString("CONN_LCLDB_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FinancialPlanner.
        /// </summary>
        internal static string CONN_SRVR_DATABASE {
            get {
                return ResourceManager.GetString("CONN_SRVR_DATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abc123*.
        /// </summary>
        internal static string CONN_SRVR_PASSWORD {
            get {
                return ResourceManager.GetString("CONN_SRVR_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LENOVO-PC\APPLICATION.
        /// </summary>
        internal static string CONN_SRVR_SERVER {
            get {
                return ResourceManager.GetString("CONN_SRVR_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fpadmin.
        /// </summary>
        internal static string CONN_SRVR_USERID {
            get {
                return ResourceManager.GetString("CONN_SRVR_USERID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 911887638900586.
        /// </summary>
        internal static string FACEBOOK_APPID {
            get {
                return ResourceManager.GetString("FACEBOOK_APPID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9e73f35cef07f403dae1ae83a0109071.
        /// </summary>
        internal static string FACEBOOK_APPSECRET {
            get {
                return ResourceManager.GetString("FACEBOOK_APPSECRET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to azure_607f1bb93191b2c9f7f4c94289989ea9@azure.com.
        /// </summary>
        internal static string SENDGRIDMAIL_LOGIN {
            get {
                return ResourceManager.GetString("SENDGRIDMAIL_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4VTfSki0a8a0wl8.
        /// </summary>
        internal static string SENDGRIDMAIL_PASSWORD {
            get {
                return ResourceManager.GetString("SENDGRIDMAIL_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to igALky6X6Zpb4rpPVZtsx9HSJ.
        /// </summary>
        internal static string TWITTER_CONSUMERKEY {
            get {
                return ResourceManager.GetString("TWITTER_CONSUMERKEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YA0ikAfOSBDzhdcNpYzhLIXKavtJZnzd1gYZ6xXDB5Dn3zLRwN.
        /// </summary>
        internal static string TWITTER_CONSUMERSECRET {
            get {
                return ResourceManager.GetString("TWITTER_CONSUMERSECRET", resourceCulture);
            }
        }
    }
}
