//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancialPlanner.Data.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ItemDetailEntities : DbContext
    {
        public ItemDetailEntities()
            : base("name=ItemDetailEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Credit> Credits { get; set; }
        public virtual DbSet<Debit> Debits { get; set; }
        public virtual DbSet<InitialAmount> InitialAmounts { get; set; }
        public virtual DbSet<Period> Periods { get; set; }
    }
}
