//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancialPlanner.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class InitialAmount
    {
        public int PkID { get; set; }
        public string UserName { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
    }
}
